apiVersion: v1
kind: Pod
metadata:
  name: q7-pod
  namespace: q7
  labels:
    app: q7-pod
spec:
  containers:
  - image: 172.30.1.1:5000/q7/q7-app 
    name: q7-php-container
    ports:
    - containerPort: 8080
      protocol: TCP

