apiVersion: v1
kind: Pod
metadata:
  name: app-init
  namespace: q5
  labels:
    app: app-init
spec:
  containers:
  - image: 172.30.1.1:5000/q5/q5-app
    name: q5-main
    volumeMounts:
    - name: data-volume
      mountPath: /opt/app-root/src/data
  initContainers:
  - name: data-volume
    image: alpine
    command: ['sh', '-c', 'echo "hello world" > /data/message']
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    emptyDir: {}
