apiVersion: v1
kind: Pod
metadata:
  name: q6-pod
  namespace: q6
  labels:
    app: q6
spec:
  containers:
  - image: 172.30.1.1:5000/q6/q6-app 
    name: q6-httpd-container
    volumeMounts:
    - name: temp-volume
      mountPath: /opt/app-root/src/temp-vol
  volumes:
  - name: temp-volume
    emptyDir: {}

